"""Load the synthetic patient-case dataset generated by data/generate_patient_cases.py."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SystemExit(f"{path} not found — run `python data/generate_patient_cases.py` first.")
    return [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]


def load_cases() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Returns (calibration_cases, test_cases)."""
    rows = _load_jsonl(DATA_DIR / "patient_cases.jsonl")
    calibration = [r for r in rows if r["split"] == "calibration"]
    test = [r for r in rows if r["split"] == "test"]
    return calibration, test


def load_claim_calibration() -> list[dict[str, Any]]:
    return _load_jsonl(DATA_DIR / "claim_calibration.jsonl")
