"""Google ADK: an AML alert investigator whose account holds pass a calibrated FDR guard.

All data here is synthetic: invented alerts, accounts and a fictional
investigation guideline. Nothing in this example is legal or regulatory
advice.

What the agent does
    A ``google.adk.agents.Agent`` investigates anti-money-laundering alerts.
    It reads an alert with ``get_alert`` (unguarded) and, when it sees a
    red-flag pattern, proposes ``place_account_hold(account_id, alert_id,
    reason)``.

The decision being guarded
    Placing a temporary hold on a customer's account. An unwarranted hold
    freezes an innocent customer's money; a missed one lets funds leave. The
    guard decides each proposed hold before the tool runs.

Primitive and guarantee
    ``Gate(guarantee="fdr", target=0.10, delta=0.10, calibration_profile="aml-holds-v1")``,
    a Learn-then-Test selective threshold. Guarantee, as the SDK states it:
    "With 90% confidence, at most 0.1 of auto-approved decisions are wrong
    (Learn-then-Test, fixed-sequence, n=360)." In words: with 90%
    confidence over the calibration draw, at most 10% of the holds the guard
    places automatically are unwarranted, on alerts like the calibration set.
    It is a bound on a rate across many holds, not a statement that any one
    hold is correct; every hold it does not auto-approve goes to an analyst.

    ``--batch`` decides a nightly queue of 40 alerts at once with
    ``client.gate_batch(contexts, gate)``: conformal selection with
    Benjamini-Hochberg, which bounds the expected fraction of unwarranted
    holds among those auto-held across the batch (finite-sample FDR).

How it plugs into ADK
    ``CLIGuardPlugin(guard)`` is registered on the ``App`` the ``Runner``
    serves, so it guards ``place_account_hold`` for every agent and sub-agent.
    allow: the tool runs. escalate: ADK tool confirmation
    (``adk_request_confirmation``) pauses the turn; the analyst's answer is
    sent back with ``confirmation_response(...)`` on the same session, and
    ADK re-runs the original call only if it was approved. block: the tool
    is skipped and the agent is told why (a Gate never blocks: it approves
    or escalates). Every decision is also written to
    ``session.state["cli_guard_audit"]``.

    The guard evaluates the case facts from the case system, built with the
    same ``alert_context()`` that built the calibration set; the agent's own
    ``reason`` text is never part of the evaluated context.

Data
    ``data/aml_alerts.jsonl``: 360 synthetic alerts with investigator
    decisions, generated by ``data/generate_aml_alerts.py`` (seeded, stdlib
    only). About half warrant a hold.

Run (from sdk/python)
    python examples/agents/google_adk/aml_account_hold_agent.py                # mock: offline, keyless
    python examples/agents/google_adk/aml_account_hold_agent.py --batch        # nightly queue, gate_batch
    python examples/agents/google_adk/aml_account_hold_agent.py --interactive  # you are the analyst

    Real providers read keys from the environment (see examples/agents/.env.example):
    OPENAI_API_KEY=...        python ... --provider openai
    AZURE_OPENAI_API_KEY=...  python ... --provider azure   (also AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT)
    ANTHROPIC_API_KEY=...     python ... --provider anthropic
    GOOGLE_API_KEY=...        python ... --provider gemini

    Gemma 4 on vLLM, as both the agent and the logprob evidence model:
        vllm serve google/gemma-4-12B-it --max-logprobs 20 --generation-config vllm \\
            --enable-auto-tool-choice --tool-call-parser gemma4
        python ... --provider vllm
    Gemma 4 on SGLang:
        python -m sglang.launch_server --model-path google/gemma-4-12B-it --port 30000 \\
            --tool-call-parser gemma4
        python ... --provider sglang
    Mix them, e.g. Claude as the agent and Gemma logprobs as the evidence:
        python ... --provider anthropic --evidence-provider vllm

    Calibration cost: the first run with a real evidence model scores the 360
    alerts once, 360 requests at access level L1 (OpenAI, Azure OpenAI, vLLM,
    SGLang) or 360 x 8 = 2,880 at L0 (Claude, Gemini: 8 samples each), and
    caches the profile in google_adk/.cli_profiles. After that each guarded
    call costs one evidence request (8 at L0); --batch adds 40 (320 at L0).

Expected output (mock)
    A-5001 (structuring): ALLOW, the hold is placed.
    A-5002 (large, documented deposit): ESCALATE, the analyst rejects, no hold.
    A-5003 (just below several thresholds): ESCALATE, the analyst approves, hold placed.
    With --batch: how many of the 40 nightly alerts were auto-held, and the
    batch guarantee. A second run reuses the cached profile and prints the
    same decisions.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import math
import re
import sys
import textwrap
from pathlib import Path
from typing import Any, Optional, Sequence

AGENTS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(AGENTS_DIR))
sys.path.insert(0, str(AGENTS_DIR / "data"))

from google.adk.agents import Agent  # noqa: E402
from google.adk.apps import App  # noqa: E402
from google.adk.runners import Runner  # noqa: E402
from google.adk.sessions import InMemorySessionService  # noqa: E402
from google.genai import types  # noqa: E402

from _shared import adk_models, calibration, display, providers  # noqa: E402
from _shared.review import Reviewer  # noqa: E402
from cli_sdk import Gate  # noqa: E402
from cli_sdk.integrations import GuardRule, ToolGuard  # noqa: E402
from cli_sdk.integrations.google_adk import (  # noqa: E402
    AUDIT_KEY,
    CLIGuardPlugin,
    confirmation_requests,
    confirmation_response,
)
from cli_sdk.local import LocalCLIClient  # noqa: E402
from generate_aml_alerts import GUIDELINE, HOLD_QUESTION, alert_context, generate  # noqa: E402

APP = "aml_investigations"
USER = "aml-ops"
NIGHTLY_SEED = 20260930
NIGHTLY_SIZE = 40

HOLD_GATE = Gate(
    instructions=HOLD_QUESTION,
    calibration_profile="aml-holds-v1",
    guarantee="fdr",
    target=0.10,
    delta=0.10,
)

INSTRUCTION = "\n".join([
    "You are an anti-money-laundering alert investigator at a bank.",
    "For the alert you are asked about:",
    "1. Call get_alert to read it.",
    "2. Compare it with the investigation guideline below.",
    "3. If any red-flag pattern is present or close to its threshold, call place_account_hold with the "
    "alert's account_id and alert_id and a one-sentence reason naming the patterns. Do not weigh the "
    "documentation yourself: every proposed hold is checked by a calibrated guard and may go to an analyst.",
    "4. If no pattern is present or close, do not place a hold; recommend closing the alert.",
    "Never retry a hold that was declined or blocked. Report the outcome in at most two sentences.",
    "",
    *GUIDELINE,
])

# ---------------------------------------------------------------------------
# the bank's systems (in-memory stand-ins)
# ---------------------------------------------------------------------------

SCENARIO_ALERTS = [
    {
        "alert_id": "A-5001", "account_id": "ACC-40317", "monitoring_rule": "cash structuring pattern",
        "customer": {"segment": "retail", "occupation_or_business": "sales associate", "tenure_months": 14,
                     "expected_monthly_deposits_usd": 4500},
        "activity_30d": {"deposits_total_usd": 61900, "cash_deposits_count": 7, "cash_deposits_total_usd": 58050,
                         "cash_deposits_8000_to_9999": 6, "largest_single_deposit_usd": 9900, "branches_used": 3,
                         "sent_out_within_48h_pct": 88, "wires_to_high_risk_jurisdictions_usd": 0},
        "documentation": {"status": "none", "note": "No explanation on file."},
        "prior_alerts_12m": 1,
    },
    {
        "alert_id": "A-5002", "account_id": "ACC-72950", "monitoring_rule": "activity above expected profile",
        "customer": {"segment": "retail", "occupation_or_business": "retired", "tenure_months": 212,
                     "expected_monthly_deposits_usd": 6000},
        "activity_30d": {"deposits_total_usd": 248600, "cash_deposits_count": 2, "cash_deposits_total_usd": 1100,
                         "cash_deposits_8000_to_9999": 0, "largest_single_deposit_usd": 243000, "branches_used": 1,
                         "sent_out_within_48h_pct": 3, "wires_to_high_risk_jurisdictions_usd": 0},
        "documentation": {"status": "verified",
                          "note": "Closing statement for a property sale on file; amount matches the deposits."},
        "prior_alerts_12m": 0,
    },
    {
        "alert_id": "A-5003", "account_id": "ACC-18864", "monitoring_rule": "rapid movement of funds",
        "customer": {"segment": "small business", "occupation_or_business": "construction subcontractor",
                     "tenure_months": 26, "expected_monthly_deposits_usd": 45000},
        "activity_30d": {"deposits_total_usd": 58000, "cash_deposits_count": 4, "cash_deposits_total_usd": 20000,
                         "cash_deposits_8000_to_9999": 2, "largest_single_deposit_usd": 21000, "branches_used": 2,
                         "sent_out_within_48h_pct": 79, "wires_to_high_risk_jurisdictions_usd": 18500},
        "documentation": {"status": "partial",
                          "note": "Customer says the funds come from a family loan; no loan agreement on file."},
        "prior_alerts_12m": 2,
    },
]

SCENARIOS = [
    ("A-5001", "six cash deposits just under 10,000 USD at three branches in 30 days"),
    ("A-5002", "a 243,000 USD deposit with a verified property-sale closing statement"),
    ("A-5003", "every measure just below a guideline threshold; partial documentation"),
]
ANALYST_SCRIPT = {"A-5002": False, "A-5003": True}


class CaseSystem:
    """Stand-in for the case-management and core-banking systems."""

    def __init__(self, alerts: Sequence[dict[str, Any]]) -> None:
        self.alerts = {a["alert_id"]: a for a in alerts}
        self.holds: list[dict[str, Any]] = []

    def hold_context(self, args: dict[str, Any]) -> dict[str, Any]:
        """The guard's context for a proposed hold: the case facts, rendered like the calibration set.

        A hold on an unknown alert, or on an account that is not the alert's,
        raises here; the guard then escalates instead of guessing.
        """
        alert = self.alerts.get(args.get("alert_id"))
        if alert is None:
            raise ValueError(f"alert {args.get('alert_id')!r} is not in the case system")
        if args.get("account_id") != alert["account_id"]:
            raise ValueError(f"account {args.get('account_id')!r} is not the account on alert {alert['alert_id']}")
        return alert_context(alert)


def make_tools(cases: CaseSystem):
    def get_alert(alert_id: str) -> dict:
        """Read an AML alert: customer profile, 30-day activity, documentation and prior alerts.

        Args:
            alert_id: The alert identifier, for example "A-5001".
        """
        alert = cases.alerts.get(alert_id)
        return alert_context(alert)["alert"] if alert else {"error": f"no alert {alert_id}"}

    def place_account_hold(account_id: str, alert_id: str, reason: str) -> dict:
        """Place a temporary hold on an account under investigation.

        Args:
            account_id: The account to hold, as shown on the alert.
            alert_id: The alert that justifies the hold.
            reason: One sentence naming the red-flag patterns observed.
        """
        hold = {"hold_id": f"HOLD-{alert_id}", "account_id": account_id, "alert_id": alert_id, "reason": reason}
        cases.holds.append(hold)
        return {"status": "hold_placed", **hold}

    return get_alert, place_account_hold


# ---------------------------------------------------------------------------
# keyless models: the scripted agent and the mock evidence model
# ---------------------------------------------------------------------------


def observed_patterns(alert: dict[str, Any]) -> list[str]:
    """What the scripted investigator notices: patterns present or close to a threshold."""
    act, customer = alert["activity_30d"], alert["customer"]
    seen = []
    if act["cash_deposits_8000_to_9999"] >= 2:
        seen.append(f"{act['cash_deposits_8000_to_9999']} cash deposits between 8,000 and 9,999 USD")
    if act["sent_out_within_48h_pct"] >= 75 and act["deposits_total_usd"] >= 20_000:
        seen.append(f"{act['sent_out_within_48h_pct']}% of deposits sent out within 48 hours")
    if act["wires_to_high_risk_jurisdictions_usd"] >= 15_000:
        seen.append(f"{act['wires_to_high_risk_jurisdictions_usd']:,} USD wired to high-risk jurisdictions")
    ratio = act["deposits_total_usd"] / max(customer["expected_monthly_deposits_usd"], 1)
    if ratio > 2.5 and act["deposits_total_usd"] >= 10_000:
        seen.append(f"deposits {ratio:.0f} times the expected monthly profile")
    return seen


def investigator_policy(history: Sequence[types.Content]) -> types.Part:
    """The scripted agent: read the alert, propose a hold when a pattern shows, report the outcome."""
    result = adk_models.last_tool_result(history)
    if result is None:
        match = re.search(r"\bA-\d{4}\b", adk_models.last_user_text(history))
        if not match:
            return adk_models.say("Which alert should I investigate?")
        return adk_models.call("get_alert", alert_id=match.group(0))
    name, response = result
    if name == "get_alert":
        if "error" in response:
            return adk_models.say(response["error"])
        patterns = observed_patterns(response)
        if not patterns:
            return adk_models.say(f"Alert {response['alert_id']} shows no red-flag pattern; I recommend closing it.")
        return adk_models.call("place_account_hold", account_id=response["account_id"],
                               alert_id=response["alert_id"], reason="; ".join(patterns) + ".")
    status = response.get("status")
    if status == "hold_placed":
        return adk_models.say(f"Placed hold {response['hold_id']} on {response['account_id']} for alert "
                              f"{response['alert_id']}.")
    if status == "rejected_by_reviewer":
        return adk_models.say("An analyst declined the hold, so none was placed. I have not retried it; "
                              "the alert stays with the analyst.")
    return adk_models.say(response.get("message") or f"The hold did not go ahead ({status}).")


def _uniform(*parts: Any) -> float:
    digest = hashlib.sha256(json.dumps(parts).encode()).digest()
    return int.from_bytes(digest[:8], "big") / 2**64


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-max(-60.0, min(60.0, x))))


def mock_hold_evidence(context: Any, instructions: Any, options: Any) -> dict[str, float]:
    """A fallible reader of the alert facts, standing in for an LLM's P(hold warranted).

    It scores the guideline's patterns softly (so values near a threshold
    are uncertain), over-trusts verified documentation a little even for
    structuring, and adds deterministic noise keyed on the alert id. It sees
    only the context; the calibration label is never passed to it.
    """
    alert = context["alert"]
    act, customer, doc = alert["activity_30d"], alert["customer"], alert["documentation"]["status"]
    s = _sigmoid((act["cash_deposits_8000_to_9999"] - 2.5) * 2.4)
    v = _sigmoid((act["sent_out_within_48h_pct"] - 79.5) / 2.5) * _sigmoid((act["deposits_total_usd"] - 25_000) / 2_500)
    j = _sigmoid((act["wires_to_high_risk_jurisdictions_usd"] - 20_000) / 2_000)
    ratio = act["deposits_total_usd"] / max(customer["expected_monthly_deposits_usd"], 1)
    p = _sigmoid((ratio - 3.0) / 0.3) * _sigmoid((act["deposits_total_usd"] - 10_000) / 1_500)
    others = v + j + p
    logit = -2.4 + 4.4 * s * (0.8 if doc == "verified" else 1.0)
    logit += {"none": 2.8, "partial": 1.1, "verified": 0.3}[doc] * others
    if doc == "partial":
        logit += 1.8 * max(0.0, others - 1.0)
    logit += 0.15 * min(alert["prior_alerts_12m"], 3)
    logit += (_uniform("aml", alert["alert_id"], 1) + _uniform("aml", alert["alert_id"], 2) - 1.0) * 1.8
    p_true = _sigmoid(logit)
    return {"true": p_true, "false": 1.0 - p_true}


# ---------------------------------------------------------------------------
# the demo
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    providers.add_arguments(parser)
    parser.add_argument("--batch", action="store_true",
                        help=f"decide a nightly queue of {NIGHTLY_SIZE} alerts with gate_batch instead")
    return parser


async def run_scenarios(client: LocalCLIClient, model: Any, reviewer: Reviewer) -> dict[str, Any]:
    cases = CaseSystem(SCENARIO_ALERTS)
    guard = ToolGuard(client, [
        GuardRule(tool="place_account_hold", query=HOLD_GATE, context=cases.hold_context),
    ])
    agent = Agent(name="aml_investigator", model=model, instruction=INSTRUCTION,
                  tools=list(make_tools(cases)))
    # App-wide: the plugin guards place_account_hold for every agent the runner drives.
    app = App(name=APP, root_agent=agent, plugins=[CLIGuardPlugin(guard)])
    sessions = InMemorySessionService()
    runner = Runner(app=app, session_service=sessions)
    outcomes: dict[str, Any] = {}
    try:
        for case_id, headline in SCENARIOS:
            display.scenario(case_id, headline)
            session = await sessions.create_session(app_name=APP, user_id=USER)
            holds_before = len(cases.holds)
            ask = f"Investigate alert {case_id} and place a hold if the guideline calls for one."
            events = await adk_models.run_turn(runner, user_id=USER, session_id=session.id,
                                               message=adk_models.user_message(ask))
            adk_models.print_turn(events, ran_status="hold_placed")
            reviewed: Optional[bool] = None
            for request in confirmation_requests(events):
                reviewed = reviewer.decide(case_id, request)
                answer = {"reviewer": "aml-analyst", "decision": "approved" if reviewed else "rejected"}
                events = await adk_models.run_turn(runner, user_id=USER, session_id=session.id,
                                                   message=confirmation_response(request["id"], reviewed, answer))
                adk_models.print_turn(events, ran_status="hold_placed")
            state = (await sessions.get_session(app_name=APP, user_id=USER, session_id=session.id)).state
            audit = [entry["action"] for entry in state.get(AUDIT_KEY, [])]
            print(f"    audit: session.state[{AUDIT_KEY!r}] = {audit}")
            outcomes[case_id] = {"action": audit[0] if audit else None, "reviewed": reviewed,
                                 "executed": len(cases.holds) > holds_before, "audit": audit,
                                 "final_text": adk_models.final_text(events)}
    finally:
        await runner.close()
    return {"scenarios": outcomes, "holds": cases.holds}


def run_batch(client: LocalCLIClient) -> dict[str, Any]:
    """Nightly mode: decide a whole queue with conformal selection + Benjamini-Hochberg."""
    queue = generate(NIGHTLY_SIZE, seed=NIGHTLY_SEED, first_id=7001)
    answers = client.gate_batch([row["context"] for row in queue], HOLD_GATE)
    held = [row for row, answer in zip(queue, answers) if answer.approved]
    unwarranted = sum(1 for row in held if not row["label"])
    warranted = sum(1 for row in queue if row["label"])
    statement = answers[0].guarantee.describe()

    def para(text: str, first: str = "    ", rest: str = "    ") -> None:
        print(textwrap.fill(text, 78, initial_indent=first, subsequent_indent=rest))

    print("-" * 78)
    para(f"Nightly queue: {NIGHTLY_SIZE} synthetic alerts from the calibration set's generator (so "
         "exchangeable with it), decided together with client.gate_batch().", "", "")
    print(f"    auto-held:        {len(held)}")
    para(" ".join(row["id"] for row in held), " " * 22, " " * 22)
    print(f"    sent to analysts: {NIGHTLY_SIZE - len(held)}")
    para(statement, "    guarantee: ", " " * 15)
    para(f"demo check, possible only because the labels are synthetic: {unwarranted} of the {len(held)} "
         f"automatic holds {'was' if unwarranted == 1 else 'were'} unwarranted, and {len(held) - unwarranted} "
         f"of the {warranted} warranted holds in the queue were placed automatically (the rest wait for an "
         "analyst). The bound is on the expected fraction across batches, so one batch can land above or "
         "below it.")
    return {"batch": {"size": NIGHTLY_SIZE, "auto_held": [row["id"] for row in held],
                      "escalated": [row["id"] for row, a in zip(queue, answers) if not a.approved],
                      "unwarranted_auto_holds": unwarranted, "statement": statement}}


def run(argv: Optional[Sequence[str]] = None, *, reviewer: Optional[Reviewer] = None) -> dict[str, Any]:
    """Run the demo and return what happened (used by the tests)."""
    args = build_parser().parse_args(argv)
    evidence_provider = args.evidence_provider or args.provider
    # Both models are built before anything else, so a placeholder key stops the run here.
    model = None if args.batch else adk_models.agent_model(args.provider, policy=investigator_policy)
    backend = providers.evidence_backend(evidence_provider, mock_scorer=mock_hold_evidence)
    client = LocalCLIClient(backend, store=calibration.default_store(__file__, args.store),
                            sample_count=providers.sample_count(evidence_provider))

    display.banner("Google ADK: AML account-hold investigator with a calibrated FDR guard", "compliance")
    agent_label = "(not used in --batch)" if args.batch else args.provider
    print(f"agent model: {agent_label}; evidence model: {evidence_provider}")
    already, _ = client.calibration_status(HOLD_GATE)
    sys.stdout.flush()  # calibration progress goes to stderr
    examples = calibration.load_jsonl("aml_alerts.jsonl")
    profile = calibration.ensure_calibrated(client, [HOLD_GATE], examples, recalibrate=args.recalibrate)[0]
    print(f"calibration: data/aml_alerts.jsonl ({len(examples)} synthetic alerts)")
    print(f"profile: {profile.name}, {profile.method}, n={profile.n} (minimum {profile.minimum_n}), "
          f"{profile.status}, {'cached' if already and not args.recalibrate else 'calibrated now'}")

    if args.batch:
        result = run_batch(client)
    else:
        reviewer = reviewer or Reviewer(interactive=args.interactive, script=ANALYST_SCRIPT, role="AML analyst")
        result = asyncio.run(run_scenarios(client, model, reviewer))
    display.footer()
    result["profile"] = {"name": profile.name, "method": profile.method, "n": profile.n, "status": profile.status,
                         "calibrated_now": not already or args.recalibrate}
    return result


def main(argv: Optional[Sequence[str]] = None) -> int:
    run(argv)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
