"""Google ADK: a clinical-trial pre-screening assistant guarded by a Venn-Abers Belief.

All data here is synthetic: invented patients and a fictional protocol,
SYN-CKD-201. This is not medical advice and not a medical device; it must
not be used to decide anyone's care or trial eligibility.

What the agent does
    A ``google.adk.agents.Agent`` reads a pre-screening record with
    ``get_prescreening_record`` (unguarded) and proposes
    ``mark_eligible(patient_id, trial_id)`` when the patient looks eligible.
    The mark is a pre-screening flag: the study team still confirms
    eligibility at the screening visit.

The decision being guarded
    Marking a patient as pre-screen eligible. A wrong mark sends an
    ineligible patient to a screening visit (or past a safety exclusion); the
    guard decides each proposed mark before the tool runs.

Primitive and guarantee
    ``Belief(instructions="Does this patient meet every inclusion criterion
    and no exclusion criterion of the protocol in the context?",
    calibration_profile="trial-screening-v1")`` returns an IVAP (Venn-Abers)
    pair [p0, p1]. The SDK's statement: "Venn-Abers pair [p0, p1]: the
    probability computed under the true label is calibrated on data
    exchangeable with the 320 calibration examples; a wide pair means the
    calibration data cannot pin the probability down." It is not a bracket
    on one patient's true probability. ``GuardRule(allow_above=0.85,
    block_below=0.15)`` maps it:

        interval entirely at or above 0.85   allow: the mark is made
        interval entirely below 0.15         block: the agent is told it cannot mark the patient
        anything else                        escalate: a research coordinator decides

    A Belief is a calibrated probability, not an error-rate bound: it does
    not promise that any one patient is eligible, and it does not cap the
    error rate of automatic marks. It only acts alone where the calibration
    data are unambiguous, on records like the calibration set, and leaves
    the rest to a person. For a stated bound on the rate of wrong automatic
    decisions, use a Gate (see the AML example).

How it plugs into ADK
    ``before_tool_callback=cli_before_tool_callback(guard)`` on this one
    agent. allow: the callback returns None and the tool runs. block: the
    callback returns a result dict, so ADK skips the tool and the model reads
    why. escalate: ``tool_context.request_confirmation(...)`` pauses the turn
    with an ``adk_request_confirmation`` call; the coordinator's answer goes
    back with ``confirmation_response(...)`` on the same session and ADK
    re-runs the original call, which executes only if approved.

    The guard evaluates the record from the screening system, built with the
    same ``screening_context()`` that built the calibration set, never the
    agent's summary of it. A mark for any trial other than SYN-CKD-201 cannot
    be evaluated against this calibration and is escalated.

Data
    ``data/trial_screening.jsonl``: 320 synthetic pre-screening records
    labelled with eligibility at the screening visit, generated by
    ``data/generate_trial_screening.py`` (seeded, stdlib only). Records whose
    labs sit near a cutoff are genuinely uncertain, because the visit
    re-measures them.

Run (from sdk/python)
    python examples/agents/google_adk/clinical_trial_screening_agent.py                # mock: offline, keyless
    python examples/agents/google_adk/clinical_trial_screening_agent.py --interactive  # you are the coordinator

    Real providers read keys from the environment (see examples/agents/.env.example):
    OPENAI_API_KEY=...        python ... --provider openai
    AZURE_OPENAI_API_KEY=...  python ... --provider azure   (also AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT)
    ANTHROPIC_API_KEY=...     python ... --provider anthropic
    GOOGLE_API_KEY=...        python ... --provider gemini

    Gemma 4 on vLLM, as both the agent and the logprob evidence model:
        vllm serve google/gemma-4-12B-it --max-logprobs 20 --generation-config vllm \\
            --enable-auto-tool-choice --tool-call-parser gemma4
        python ... --provider vllm
    Gemma 4 on SGLang:
        python -m sglang.launch_server --model-path google/gemma-4-12B-it --port 30000 \\
            --tool-call-parser gemma4
        python ... --provider sglang

    Calibration cost: the first run with a real evidence model scores the 320
    records once, 320 requests at access level L1 (OpenAI, Azure OpenAI,
    vLLM, SGLang) or 320 x 8 = 2,560 at L0 (Claude, Gemini: 8 samples each),
    and caches the profile in google_adk/.cli_profiles. After that each
    guarded call costs one evidence request (8 at L0).

Expected output (mock)
    P-6001 (clearly eligible): ALLOW, the patient is marked.
    P-6002 (eGFR 59 and HbA1c 10.4%, each at the edge of its range): ESCALATE,
        the coordinator approves, marked.
    P-6003 (SGLT2 inhibitor stopped 5 weeks ago): BLOCK, not marked; the agent says so.
    The scripted agent checks age, diagnosis and labs but, like a hurried
    reader, not medication history, which is why it proposes P-6003 at all.
    A second run reuses the cached profile and prints the same decisions.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import math
import re
import sys
from pathlib import Path
from typing import Any, Optional, Sequence

AGENTS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(AGENTS_DIR))
sys.path.insert(0, str(AGENTS_DIR / "data"))

from google.adk.agents import Agent  # noqa: E402
from google.adk.apps import App  # noqa: E402
from google.adk.runners import Runner  # noqa: E402
from google.adk.sessions import InMemorySessionService  # noqa: E402
from google.genai import types  # noqa: E402

from _shared import adk_models, calibration, display, providers  # noqa: E402
from _shared.review import Reviewer  # noqa: E402
from cli_sdk import Belief  # noqa: E402
from cli_sdk.integrations import GuardRule, ToolGuard  # noqa: E402
from cli_sdk.integrations.google_adk import (  # noqa: E402
    AUDIT_KEY,
    cli_before_tool_callback,
    confirmation_requests,
    confirmation_response,
)
from cli_sdk.local import LocalCLIClient  # noqa: E402
from generate_trial_screening import ELIGIBILITY_QUESTION, PROTOCOL, TRIAL_ID, screening_context  # noqa: E402

APP = "trial_prescreening"
USER = "research-coordination"

ELIGIBILITY = Belief(instructions=ELIGIBILITY_QUESTION, calibration_profile="trial-screening-v1")

INSTRUCTION = "\n".join([
    "You are a clinical-trial pre-screening assistant for a research site.",
    "For the patient you are asked about:",
    "1. Call get_prescreening_record to read the record.",
    f"2. Compare it with every criterion of protocol {TRIAL_ID} below.",
    f"3. If the patient appears to meet every inclusion criterion and no exclusion criterion, call "
    f"mark_eligible with the patient_id and trial_id {TRIAL_ID}. Every mark is checked by a calibrated "
    "guard and may go to a research coordinator.",
    "4. Otherwise do not mark the patient; say which criterion is not met.",
    "Never retry a mark that was declined or blocked. Do not give medical advice. Report the outcome in "
    "at most two sentences.",
    "",
    *PROTOCOL,
])

# ---------------------------------------------------------------------------
# the site's screening system (in-memory stand-in)
# ---------------------------------------------------------------------------


def _meds(*items: tuple[str, str, int]) -> list[dict[str, Any]]:
    return [{"drug": d, "drug_class": c, "weeks_since_last_dose": w} for d, c, w in items]


SCENARIO_RECORDS = [
    {
        "patient_id": "P-6001", "age_years": 58, "sex": "female",
        "diagnoses": ["type 2 diabetes mellitus", "chronic kidney disease stage 3", "hypertension"],
        "labs_most_recent": {"egfr_ml_min_1_73m2": 44, "hba1c_percent": 8.1, "alt_x_uln": 0.9},
        "medications": _meds(("metformin", "other", 0), ("lisinopril", "other", 0)),
        "dialysis_or_kidney_transplant": False, "pregnant_breastfeeding_or_planning": False,
        "interventional_study_last_30_days": False,
    },
    {
        "patient_id": "P-6002", "age_years": 66, "sex": "male",
        "diagnoses": ["type 2 diabetes mellitus", "chronic kidney disease stage 3", "hyperlipidemia"],
        "labs_most_recent": {"egfr_ml_min_1_73m2": 59, "hba1c_percent": 10.4, "alt_x_uln": 1.1},
        "medications": _meds(("metformin", "other", 0), ("insulin glargine", "other", 0),
                             ("atorvastatin", "other", 0)),
        "dialysis_or_kidney_transplant": False, "pregnant_breastfeeding_or_planning": False,
        "interventional_study_last_30_days": False,
    },
    {
        "patient_id": "P-6003", "age_years": 61, "sex": "female",
        "diagnoses": ["type 2 diabetes mellitus", "chronic kidney disease stage 3", "obesity"],
        "labs_most_recent": {"egfr_ml_min_1_73m2": 41, "hba1c_percent": 7.9, "alt_x_uln": 0.7},
        "medications": _meds(("metformin", "other", 0), ("dapagliflozin", "SGLT2 inhibitor", 5)),
        "dialysis_or_kidney_transplant": False, "pregnant_breastfeeding_or_planning": False,
        "interventional_study_last_30_days": False,
    },
]

SCENARIOS = [
    ("P-6001", "age 58, eGFR 44, HbA1c 8.1%, no exclusions on record"),
    ("P-6002", "eGFR 59 and HbA1c 10.4%, both at the edge of re-measured ranges"),
    ("P-6003", "dapagliflozin (an SGLT2 inhibitor) stopped 5 weeks ago"),
]
COORDINATOR_SCRIPT = {"P-6002": True}


class ScreeningSystem:
    """Stand-in for the site's pre-screening records and trial-management system."""

    def __init__(self, records: Sequence[dict[str, Any]]) -> None:
        self.records = {r["patient_id"]: r for r in records}
        self.marked: list[dict[str, str]] = []

    def eligibility_context(self, args: dict[str, Any]) -> dict[str, Any]:
        """The guard's context for a proposed mark: the record, rendered like the calibration set.

        Only SYN-CKD-201 was calibrated, so a mark for another trial (or an
        unknown patient) raises here and the guard escalates.
        """
        if args.get("trial_id") != TRIAL_ID:
            raise ValueError(f"trial {args.get('trial_id')!r} has no calibration profile; only {TRIAL_ID} does")
        record = self.records.get(args.get("patient_id"))
        if record is None:
            raise ValueError(f"patient {args.get('patient_id')!r} has no pre-screening record")
        return screening_context(record)


def make_tools(system: ScreeningSystem):
    def get_prescreening_record(patient_id: str) -> dict:
        """Read a patient's pre-screening record: age, diagnoses, recent labs, medications, exclusions.

        Args:
            patient_id: The patient identifier, for example "P-6001".
        """
        record = system.records.get(patient_id)
        return screening_context(record)["patient"] if record else {"error": f"no record for {patient_id}"}

    def mark_eligible(patient_id: str, trial_id: str) -> dict:
        """Flag a patient as pre-screen eligible for a trial, for the study team to confirm at screening.

        Args:
            patient_id: The patient identifier.
            trial_id: The trial identifier, for example "SYN-CKD-201".
        """
        system.marked.append({"patient_id": patient_id, "trial_id": trial_id})
        return {"status": "marked_eligible", "patient_id": patient_id, "trial_id": trial_id}

    return get_prescreening_record, mark_eligible


# ---------------------------------------------------------------------------
# keyless models: the scripted agent and the mock evidence model
# ---------------------------------------------------------------------------


def looks_eligible(record: dict[str, Any]) -> bool:
    """The scripted agent's check: age, diagnosis and labs only. It never reads medications."""
    labs = record["labs_most_recent"]
    return (18 <= record["age_years"] <= 75 and "type 2 diabetes mellitus" in record["diagnoses"]
            and 30 <= labs["egfr_ml_min_1_73m2"] <= 59 and 7.0 <= labs["hba1c_percent"] <= 10.5)


def prescreener_policy(history: Sequence[types.Content]) -> types.Part:
    """The scripted agent: read the record, propose a mark when it looks eligible, report the outcome."""
    result = adk_models.last_tool_result(history)
    patient = re.search(r"\bP-\d{4}\b", adk_models.last_user_text(history))
    patient_id = patient.group(0) if patient else "the patient"
    if result is None:
        if not patient:
            return adk_models.say("Which patient should I pre-screen?")
        return adk_models.call("get_prescreening_record", patient_id=patient_id)
    name, response = result
    if name == "get_prescreening_record":
        if "error" in response:
            return adk_models.say(response["error"])
        if not looks_eligible(response):
            return adk_models.say(f"{patient_id} does not meet the age, diagnosis or lab criteria of {TRIAL_ID}; "
                                  "I have not marked them.")
        return adk_models.call("mark_eligible", patient_id=patient_id, trial_id=TRIAL_ID)
    status = response.get("status")
    if status == "marked_eligible":
        return adk_models.say(f"Marked {patient_id} as pre-screen eligible for {TRIAL_ID}; the study team "
                              "confirms eligibility at the screening visit.")
    if status == "rejected_by_reviewer":
        return adk_models.say(f"The research coordinator declined to mark {patient_id}; I have not retried it.")
    if status == "blocked":
        return adk_models.say(f"I cannot mark {patient_id} as eligible for {TRIAL_ID}: the calibrated check "
                              "blocked it. The record stays in the coordinator's standard screening queue.")
    return adk_models.say(response.get("message") or f"The mark did not go ahead ({status}).")


def _uniform(*parts: Any) -> float:
    digest = hashlib.sha256(json.dumps(parts).encode()).digest()
    return int.from_bytes(digest[:8], "big") / 2**64


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-max(-60.0, min(60.0, x))))


def _window(x: float, low: float, high: float, scale: float) -> float:
    return _sigmoid((x - low) / scale) * _sigmoid((high - x) / scale)


def mock_eligibility_evidence(context: Any, instructions: Any, options: Any) -> dict[str, float]:
    """A fallible reader of the record, standing in for an LLM's P(eligible).

    Each criterion is read softly, so labs near a cutoff are uncertain. On
    about 12% of records (chosen by patient id) it slips and overlooks the
    SGLT2 washout and the ALT, pregnancy and study exclusions, the kind of
    confident mistake calibration has to absorb. Deterministic noise is keyed
    on the patient id. It sees only the context, never the label.
    """
    patient = context["patient"]
    labs, pid = patient["labs_most_recent"], patient["patient_id"]
    slip = _uniform("trial-slip", pid) < 0.12
    met = _window(patient["age_years"], 17.5, 75.5, 0.5)
    met *= 0.98 if "type 2 diabetes mellitus" in patient["diagnoses"] else 0.03
    met *= _window(labs["egfr_ml_min_1_73m2"], 29.5, 59.5, 1.6)
    met *= _window(labs["hba1c_percent"], 6.95, 10.55, 0.15)
    if not slip:
        weeks = [m["weeks_since_last_dose"] for m in patient["medications"] if m["drug_class"] == "SGLT2 inhibitor"]
        if weeks:
            met *= _sigmoid((min(weeks) - 12) / 1.2)
        met *= _sigmoid((3.0 - labs["alt_x_uln"]) / 0.2)
        if patient["pregnant_breastfeeding_or_planning"]:
            met *= 0.04
        if patient["interventional_study_last_30_days"]:
            met *= 0.2
    if "type 1 diabetes mellitus" in patient["diagnoses"]:
        met *= 0.05
    if patient["dialysis_or_kidney_transplant"]:
        met *= 0.04
    met = min(max(met, 1e-4), 1 - 1e-4)
    logit = math.log(met / (1 - met)) + (_uniform("trial", pid, 1) + _uniform("trial", pid, 2) - 1.0) * 1.4
    p_true = _sigmoid(logit)
    return {"true": p_true, "false": 1.0 - p_true}


# ---------------------------------------------------------------------------
# the demo
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    return providers.add_arguments(parser)


def build_agent(model: Any, guard: ToolGuard, system: ScreeningSystem) -> Agent:
    return Agent(
        name="trial_prescreener",
        model=model,
        instruction=INSTRUCTION,
        tools=list(make_tools(system)),
        before_tool_callback=cli_before_tool_callback(guard),
    )


async def run_scenarios(client: LocalCLIClient, model: Any, reviewer: Reviewer) -> dict[str, Any]:
    system = ScreeningSystem(SCENARIO_RECORDS)
    guard = ToolGuard(client, [
        GuardRule(tool="mark_eligible", query=ELIGIBILITY, context=system.eligibility_context,
                  allow_above=0.85, block_below=0.15),
    ])
    sessions = InMemorySessionService()
    runner = Runner(app=App(name=APP, root_agent=build_agent(model, guard, system)),
                    session_service=sessions)
    outcomes: dict[str, Any] = {}
    try:
        for patient_id, headline in SCENARIOS:
            display.scenario(patient_id, headline)
            session = await sessions.create_session(app_name=APP, user_id=USER)
            marked_before = len(system.marked)
            ask = f"Pre-screen patient {patient_id} for trial {TRIAL_ID}."
            events = await adk_models.run_turn(runner, user_id=USER, session_id=session.id,
                                               message=adk_models.user_message(ask))
            adk_models.print_turn(events, ran_status="marked_eligible")
            reviewed: Optional[bool] = None
            for request in confirmation_requests(events):
                reviewed = reviewer.decide(patient_id, request)
                answer = {"reviewer": "research-coordinator", "decision": "approved" if reviewed else "rejected"}
                events = await adk_models.run_turn(runner, user_id=USER, session_id=session.id,
                                                   message=confirmation_response(request["id"], reviewed, answer))
                adk_models.print_turn(events, ran_status="marked_eligible")
            state = (await sessions.get_session(app_name=APP, user_id=USER, session_id=session.id)).state
            audit = state.get(AUDIT_KEY, [])
            print(f"    audit: session.state[{AUDIT_KEY!r}] = {[entry['action'] for entry in audit]}")
            evidence = (audit[0].get("evidence") or {}) if audit else {}
            outcomes[patient_id] = {"action": audit[0]["action"] if audit else None, "reviewed": reviewed,
                                    "executed": len(system.marked) > marked_before,
                                    "audit": [entry["action"] for entry in audit],
                                    "venn_abers": evidence.get("venn_abers"),
                                    "final_text": adk_models.final_text(events)}
    finally:
        await runner.close()
    return {"scenarios": outcomes, "marked": system.marked}


def run(argv: Optional[Sequence[str]] = None, *, reviewer: Optional[Reviewer] = None) -> dict[str, Any]:
    """Run the demo and return what happened (used by the tests)."""
    args = build_parser().parse_args(argv)
    evidence_provider = args.evidence_provider or args.provider
    # Both models are built before anything else, so a placeholder key stops the run here.
    model = adk_models.agent_model(args.provider, policy=prescreener_policy)
    backend = providers.evidence_backend(evidence_provider, mock_scorer=mock_eligibility_evidence)
    client = LocalCLIClient(backend, store=calibration.default_store(__file__, args.store),
                            sample_count=providers.sample_count(evidence_provider))

    display.banner("Google ADK: clinical-trial pre-screening with a Venn-Abers guard", "healthcare")
    print(f"agent model: {args.provider}; evidence model: {evidence_provider}")
    already, _ = client.calibration_status(ELIGIBILITY)
    sys.stdout.flush()  # calibration progress goes to stderr
    examples = calibration.load_jsonl("trial_screening.jsonl")
    profile = calibration.ensure_calibrated(client, [ELIGIBILITY], examples, recalibrate=args.recalibrate)[0]
    print(f"calibration: data/trial_screening.jsonl ({len(examples)} synthetic records)")
    print(f"profile: {profile.name}, {profile.method}, n={profile.n} (minimum {profile.minimum_n}), "
          f"{profile.status}, {'cached' if already and not args.recalibrate else 'calibrated now'}")
    print("rule: allow if p0 >= 0.85; block if p1 < 0.15; otherwise a coordinator decides")

    reviewer = reviewer or Reviewer(interactive=args.interactive, script=COORDINATOR_SCRIPT,
                                    role="research coordinator")
    result = asyncio.run(run_scenarios(client, model, reviewer))
    display.footer()
    result["profile"] = {"name": profile.name, "method": profile.method, "n": profile.n, "status": profile.status,
                         "calibrated_now": not already or args.recalibrate}
    return result


def main(argv: Optional[Sequence[str]] = None) -> int:
    run(argv)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
