"""Compare the baseline and CCI-guarded pipelines over the same held-out test set.

Reads results/baseline.jsonl and results/cci.jsonl (run both pipelines
first), prints a report, and writes it to results/report.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"


def load(name: str) -> dict[str, dict]:
    path = RESULTS / name
    if not path.exists():
        raise SystemExit(f"{path} not found — run the pipeline that produces it first.")
    rows = [json.loads(line) for line in path.open(encoding="utf-8")]
    return {r["case_id"]: r for r in rows}


def pct(n: int, d: int) -> str:
    return "n/a" if d == 0 else f"{100 * n / d:.0f}%"


def build_report(baseline: dict[str, dict], cci: dict[str, dict]) -> str:
    case_ids = sorted(baseline.keys())
    n = len(case_ids)

    b_rows = [baseline[c] for c in case_ids]
    b_correct = sum(1 for r in b_rows if r["predicted_urgency"] == r["true_urgency"])
    b_auto_sent = [r for r in b_rows if r["auto_sent"]]
    b_auto_wrong = [r for r in b_auto_sent if r["predicted_urgency"] != r["true_urgency"]]
    b_auto_high_acuity = [r for r in b_auto_sent if r["true_urgency"] in ("urgent_care", "emergency")]
    b_avg_conf_auto = sum(r["confidence"] for r in b_auto_sent) / len(b_auto_sent) if b_auto_sent else 0.0

    c_rows = [cci[c] for c in case_ids]
    c_covered = sum(1 for r in c_rows if r["true_urgency"] in r.get("predicted_set", [r["predicted_urgency"]]))
    c_auto_sent = [r for r in c_rows if r["auto_sent"]]
    c_auto_wrong = [r for r in c_auto_sent if r["predicted_urgency"] != r["true_urgency"]]
    c_gate_calls = [r for r in c_rows if r.get("gate_decision") is not None]
    c_gate_approved = [r for r in c_gate_calls if r["gate_decision"] == "auto_approve"]
    c_gate_approved_wrong = [r for r in c_gate_approved if r["predicted_urgency"] != r["true_urgency"]]
    c_high_acuity_escalated = sum(
        1 for r in c_rows if r["true_urgency"] in ("urgent_care", "emergency") and not r["auto_sent"]
    )
    c_total_dropped = sum(len(r.get("dropped_claims", [])) for r in c_rows)
    c_total_retained = sum(len(r.get("retained_claims", [])) for r in c_rows)

    guarantee_lines = sorted({r["set_guarantee"] for r in c_rows if r.get("set_guarantee")})
    gate_guarantee_lines = sorted({r["gate_guarantee"] for r in c_rows if r.get("gate_guarantee")})
    claim_guarantee_lines = sorted({r["claim_guarantee"] for r in c_rows if r.get("claim_guarantee")})

    lines: list[str] = []
    w = lines.append

    w("# Patient-portal triage: baseline vs. CCI-guarded — comparison report\n")
    w("**Synthetic demo data only. Not medical advice, not a medical device.**\n")
    w(f"Held-out test set: {n} cases, generated by `data/generate_patient_cases.py` "
      f"(seeded, deterministic). Both pipelines use the same Claude model for drafting; "
      f"the only variable is whether CCI's calibrated layer sits in front of what gets "
      f"auto-sent.\n")

    w("## Headline numbers\n")
    w("| | Baseline (no CCI) | CCI-guarded |")
    w("|---|---|---|")
    w(f"| Urgency accuracy (top guess) | {pct(b_correct, n)} ({b_correct}/{n}) | "
      f"{pct(c_covered, n)} candidate-set coverage ({c_covered}/{n}) |")
    w(f"| Auto-sent to patient | {pct(len(b_auto_sent), n)} ({len(b_auto_sent)}/{n}) | "
      f"{pct(len(c_auto_sent), n)} ({len(c_auto_sent)}/{n}) |")
    w(f"| Auto-sent AND wrong | {len(b_auto_wrong)} | {len(c_auto_wrong)} |")
    w(f"| Auto-sent, high-acuity (urgent/emergency) | {len(b_auto_high_acuity)} | 0 (by design) |")
    w(f"| Avg. confidence/score on auto-sent cases | {b_avg_conf_auto:.2f} (self-reported, no stated meaning) | "
      f"n/a — none auto-sent in this run |")
    w(f"| Claims caught and dropped before reaching patient | not checked (no mechanism) | "
      f"{c_total_dropped} dropped, {c_total_retained} retained |\n")

    w("## What the numbers mean\n")
    w(f"**Baseline auto-sent {len(b_auto_sent)} of {n} replies**, including "
      f"**{len(b_auto_high_acuity)} at urgent_care/emergency severity**, purely because its own "
      f"self-reported confidence cleared an arbitrary 0.8 cutoff. That number has no stated "
      f"error-rate meaning — it is the model's own opinion of itself, not an audited bound. "
      f"In this run every auto-sent case happened to be classified correctly "
      f"({len(b_auto_wrong)} wrong-and-auto-sent), which is exactly the risk: nothing in the "
      f"baseline's design would have stopped it from auto-sending a *wrong* emergency-level "
      f"reply with the same unearned confidence.\n")
    w(f"**CCI auto-sent {len(c_auto_sent)} of {n} replies in this run.** Every "
      f"urgent_care/emergency case ({c_high_acuity_escalated} of them) was escalated to a human "
      f"nurse queue regardless of how confident the underlying model was — a categorical policy "
      f"enforced by the pipeline's structure (only a singleton, low-acuity candidate set is even "
      f"considered for auto-send), not a probability. For the low-acuity cases, the `Claim` check "
      f"({c_total_dropped} claims dropped across the run, {c_total_retained} retained) turned out to "
      f"be strict enough that at least one claim in every drafted reply failed to clear the "
      f"calibrated support threshold — usually a generic recommendation sentence the small "
      f"(~48-example) calibration set and the sampling-based Claude evidence scorer couldn't yet "
      f"back with enough confidence. That is the system correctly saying *I don't have enough "
      f"evidence to certify this exact reply* rather than guessing: fail-closed by design, matching "
      f"the product's own documentation. With the ~1,000-example calibration set the docs recommend "
      f"for production use, the same mechanism would start clearing genuinely well-supported replies "
      f"while still catching the same kind of drop seen here.\n")

    w("## Guarantee cards actually returned (verbatim)\n")
    for line in guarantee_lines:
        w(f"- Set: {line}")
    for line in gate_guarantee_lines:
        w(f"- Gate: {line}")
    for line in claim_guarantee_lines:
        w(f"- Claim: {line}")
    w("")

    w("## Where the two pipelines diverged\n")
    for cid in case_ids:
        b, c = baseline[cid], cci[cid]
        if b["auto_sent"] != c["auto_sent"] or b["predicted_urgency"] != c["predicted_urgency"]:
            w(f"### {cid} (true: {b['true_urgency']}, trap: {b['is_trap']})")
            w(f"- Baseline: predicted `{b['predicted_urgency']}`, confidence {b['confidence']:.2f}, "
              f"auto_sent={b['auto_sent']}")
            w(f"  > {b['explanation']}")
            w(f"- CCI: predicted `{c['predicted_urgency']}`, auto_sent={c['auto_sent']}, "
              f"reason: {c['escalation_reason'] or 'auto-sent'}")
            if c.get("retained_claims"):
                w(f"  > {' '.join(c['retained_claims'])}")
            w("")

    w("## Trap cases (casual phrasing describing red-flag facts)\n")
    w("| Case | True | Baseline pred (conf) | Baseline auto-sent? | CCI pred | CCI auto-sent? |")
    w("|---|---|---|---|---|---|")
    for cid in case_ids:
        b, c = baseline[cid], cci[cid]
        if b["is_trap"]:
            w(f"| {cid} | {b['true_urgency']} | {b['predicted_urgency']} ({b['confidence']:.2f}) | "
              f"{b['auto_sent']} | {c['predicted_urgency']} | {c['auto_sent']} |")

    return "\n".join(lines) + "\n"


def main() -> None:
    baseline = load("baseline.jsonl")
    cci = load("cci.jsonl")
    report = build_report(baseline, cci)
    out_path = RESULTS / "report.md"
    out_path.write_text(report, encoding="utf-8")
    print(report)
    print(f"\n(written to {out_path})", file=sys.stderr)


if __name__ == "__main__":
    main()
